---
title: "Manuscript"
author: "Kyra Baranick"
editor: visual
references: references.bib
csl: ecology.csl

format:
  pdf:
    pdf-engine: xelatex
    documentclass: article
    titlepage: true
    geometry: margin=1in
    fontsize: 12pt
    include-in-header:
      text: |
        \usepackage{lineno}
        \linenumbers
        \usepackage{authblk}
  docx: default

execute:
  echo: false
  warning: false
  message: false
---

# Analysis of free-flowing rivers in the U.S. northwest as an effect of shifting climate regimes

\*\* Robert Hall PhD., Nanette Nelson, Kyra R. Baranick \*\*

Flathead Lake Biological Station, University of Montana\
Polson, MT, USA

## Introduction

(description of area)

Much of the river and stream flow regime in the Western north America is dominated by annual snowfall accumulation coupled with spring snow melt and runoff cycles. In the mountainous western U.S., it is estimated that over 50% [@articledoi:10.1061/(ASCE)1084-0699(2008)13:3(156)]and as high as 80% [@articlezheng2018predictive,] of the annual stream discharge originates as snow. The timing of snow melt hydrologic pulses has implications for water availability, ecological health and impacts to human safety. In an ideal system, precipitation falls and accumulated as snow pack acting as a natural reservoir, holding water in the form of Snow Water Equivalent (SWE). This water is released as seasons naturally shift to warm dry months, supplying water annually to downstream users. Many U.S rivers are a part of a dammed – or in other ways altered system – to mangage water supply and protect cities and ecosystems from unprecedented high and low flows. However, the mountainous western portion of the US contains the highest portion of wild and scenic, free-flowing rivers in the conterminous United States [@articlebenke1990perspective]. This study focuses on montians west of the cascades, as the climate in the Northern U.S. Rocky Mountain region is much more continental, with a larger annual average temperature range of about 5 larger then the coastal western ranges [@articleprice1978mountains,].

Being a source of many major rivers, hydrology in these areas are sensitive to climate change particularly, temperature changes[@articlebeniston2003climatic,]. Assuming 21st century warming trends – using business-as-usual green house emissions – the Parallel Climate Model (PCM) predicted stream flow timing across Western North America is expected to shift to and earlier snow melt then currently observed [@articlestewart2004changes}].

(why it matters)

With more variable flows and more connected floodplains, quantifying the significance of climate change influence on snow melt driven runoff is crucial for updated emergency response and keeping humans protected from flood related disasters.

(how this study will bring soemthing new)

While many previous studies have used remotly sensed estimates of decreasing snow pack and snow water equivalent to estimate climate induced hydro-logic changes in the west, fewer studies use in-situ USGS stream gage data to investigate long term changes on a site by site basis. [@articlehall2015detection,]

## Data

Daily and Instantaneous stream gage data was retrieved from United States Geologic Survey (USGS). Rivers and streams were selected in free-flowing watersheds that drained mountainous regions of the Northwestern United States. Watersheds that contained dams, diversions, flow altering infrastructure or agricultural land greater then 1% (percentage of drainage area) were not eligible for this study. On each identified river, the most upstream stream gage that began operation before 1950 and is still in operation as of 2026 was selected. All selected sites contained over 70 years of data, some gages contained 110+years of measurements.
